---
kind: pipeline
name: default
steps:
- name: publish_server
  image: plugins/docker
  settings:
    tags:
    - latest
    - "${DRONE_BUILD_NUMBER}"
    dockerfile: Dockerfile
    password:
      from_secret: DOCKER_PASSWORD
    repo: mcash/mcashchain-wiki
    purge: false
    username:
      from_secret: DOCKER_USERNAME
  when:
    branch:
    - master
    event:
    - push
    - tag
- name: deploy
  image: deploy
  when:
    branch:
    - master
    event:
    - push
    - tag
  environment:
    IMAGE_TAG: "${DRONE_BUILD_NUMBER}"
    KUBE_CONFIG_PATH:
      from_secret: KUBE_CONFIG_PATH
    GKE_NAMESPACE:
      from_secret: GKE_NAMESPACE
    DEPLOY_CHART_NAME: mcashchain-wiki
    CHART_PATH: ./helm
  commands:
  - helm --kubeconfig=$KUBE_CONFIG_PATH upgrade -i $DEPLOY_CHART_NAME $CHART_PATH --namespace=$GKE_NAMESPACE --set image.tag=$IMAGE_TAG
