image:
  repository: mcash/mcashchain-wiki
  pullPolicy: Always
  tag: latest

modules:
  service:
    name: service
    replicaCount: 1
    port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx/client_max_body_size: 50m
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
  rules:
  - path: /
    module: service
    hosts:
    - developer.mcash.network
  tls:
  - secretName: developer-mcash-network-tls
    hosts:
    - developer.mcash.network

resources:
  limits:
    memory: 20Mi
  requests:
    cpu: 50m
    memory: 20Mi

nodeSelector: {}

tolerations: []

affinity: {}
